name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.PHIMHAY247_PK }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa

      - name: Set up known hosts
        run: ssh-keyscan -t rsa ${{ secrets.PHIMHAY247_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          rsync -ru --ignore-existing --exclude-from=$GITHUB_WORKSPACE/.rsyncignore $GITHUB_WORKSPACE/ ${{ secrets.PHIMHAY247_USERNAME }}@${{ secrets.PHIMHAY247_IP }}:/home/phimhay247z-apiv1/htdocs/apiv1.phimhay247z.org

      - name: Start app on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PHIMHAY247_IP }}
          username: ${{ secrets.PHIMHAY247_USERNAME }}
          key: ${{ secrets.PHIMHAY247_PK }}
          script: |
            cd /home/phimhay247z-apiv1/htdocs/apiv1.phimhay247z.org
            /home/azure/.nvm/versions/node/v19.9.0/bin/pm2 reload pm2-config.json
